c = rbind(c(1, -1/2), c(-1/2, 1))
print("Our matrix c")
print(c)
cinv = solve(c)
print("Inverse of c")
print(cinv)
print("Test solve")
print(cinv %*% c)
print("Csh is cache matrix")
csh <- makeCacheMatrix(c)
print(csh)
csinv <- cacheSolve(csh)
print("Test uncached solve")
print(csinv %*% csh$get())
csh$setinverse(csinv)
cshinv <- cacheSolve(csh)
print("Test cached solve")
print(cacheSolve(csh) %*% csh$get())
