c = rbind(c(1, -1/2), c(-1/2, 1))
print("Our matrix c")
print(c)
cinv = solve(c)
print("Inverse of c")
print(cinv)
print("Test solve")
print(cinv %*% c)
print("Csh is cache matrix")
csh <- makeCacheMatrix(c)
# print(csh)
csinv <- cacheSolve(csh)
print("Test uncached solve")
print(csinv %*% csh$get())
cshinv <- cacheSolve(csh)
print("Test cached solve")
print(cacheSolve(csh) %*% csh$get())
print("What if we change it")
csh$set(rbind(c(1/4, -1/2), c(-1/2, 1/4)))
print("Test if changed")
print(cacheSolve(csh) %*% csh$get())
print("Notice that 'getting cached data' wasn't printed")
